# Generated by Django 5.0.3 on 2024-04-03 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_DoorLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doorlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.doorlock')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
    ]
