# Generated by Django 5.0.3 on 2024-04-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('control', '0002_group_doorlock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group_DoorLock',
            new_name='GroupDoorLock',
        ),
        migrations.AlterField(
            model_name='doorlock',
            name='key',
            field=models.CharField(max_length=200, verbose_name='密钥'),
        ),
        migrations.AlterField(
            model_name='doorlock',
            name='name',
            field=models.CharField(max_length=200, verbose_name='名称'),
        ),
    ]
