# Generated by Django 5.0.3 on 2024-04-03 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_remove_groupdoorlock_doorlock_groupdoorlock_doorlock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdoorlock',
            name='comment',
            field=models.CharField(default=123, max_length=200, verbose_name='描述'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserDoorLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='描述')),
                ('doorlock', models.ManyToManyField(to='control.doorlock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
