# Generated by Django 5.0.3 on 2024-04-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_groupdoorlock_comment_userdoorlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdoorlock',
            name='expireTime',
            field=models.DateTimeField(default="2024-04-03", verbose_name='过期时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdoorlock',
            name='expireTime',
            field=models.DateTimeField(default="2024-04-03", verbose_name='过期时间'),
            preserve_default=False,
        ),
    ]
