# Generated by Django 5.0.3 on 2024-04-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_groupdoorlock_expiretime_userdoorlock_expiretime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doorlock',
            options={'verbose_name': '门禁', 'verbose_name_plural': '门禁'},
        ),
        migrations.AlterModelOptions(
            name='groupdoorlock',
            options={'verbose_name': '用户组授权', 'verbose_name_plural': '用户组授权'},
        ),
        migrations.AlterModelOptions(
            name='userdoorlock',
            options={'verbose_name': '用户授权', 'verbose_name_plural': '用户授权'},
        ),
        migrations.AddField(
            model_name='doorlock',
            name='rolling_code',
            field=models.BigIntegerField(default=0, verbose_name='滚码'),
        ),
    ]
