# Generated by Django 5.0.3 on 2024-05-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_alter_doorlock_options_alter_groupdoorlock_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupdoorlock',
            options={'verbose_name': '门禁用户组授权', 'verbose_name_plural': '门禁用户组授权'},
        ),
        migrations.AlterModelOptions(
            name='userdoorlock',
            options={'verbose_name': '门禁用户授权', 'verbose_name_plural': '门禁用户授权'},
        ),
        migrations.AddField(
            model_name='doorlock',
            name='last_seen',
            field=models.DateTimeField(default=None, verbose_name='上次心跳'),
        ),
    ]
