# Generated by Django 5.0.3 on 2024-05-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_alter_doorlock_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorlock',
            name='comment',
            field=models.CharField(default=None, max_length=200, verbose_name='简介'),
            preserve_default=False,
        ),
    ]
